spring:
  data:
    mongodb:
      #uri: mongodb://name:pass@localhost:27017/tes
      host: 39.106.141.187
      port: 27017
      database: zhihu-api
      username: liudw
      password: liudw
#     grid-fs-database: test_file
