oss:
  minio:
    enabled: true
    endpoint: http://localhost:9000
    accessKey: admin
    secretKey: admin123
#  aliyun:
#    enabled: true
#  qiniu:
#    enabled: true
#    endpoint: XXX
#    accessKey: XXX
#    secretKey: XXX
#    zone: z0


