oss:
  minio:
    enabled: true
    endpoint: http://39.106.141.187:9000
    accessKey: admin
    secretKey: admin123456


#  aliyun:
#    enabled: true
#  qiniu:
#    enabled: true
#    endpoint: XXX
#    accessKey: XXX
#    secretKey: XXX
#    zone: z0
server:
  port: 18080
  tomcat:
    max-swallow-size: -1

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
