oss:
  minio:
    enabled: true
    endpoint: http://192.168.1.156:9000
    accessKey: admin
    secretKey: admin123456

#  aliyun:
#    enabled: true
#  qiniu:
#    enabled: true
#    endpoint: XXX
#    accessKey: XXX
#    secretKey: XXX
#    zone: z0


